### PR TITLE
Try to fix almost all broken links.

### PR DESCRIPTION
**Pull request by gslin**
Try to fix almost all broken links with these methods:

* Use HTTPS links if available.
* Use Internet Archive's links if the original site is not available.
* Update to new links, e.g. Microsoft-related links and Google Research links.

### CODE REVIEW

**Comment by sreeram-dev** [comment]
Waiting for it to be merged :)

**Comment by abarrak** [comment]
@dancres Yes, waiting too for kind merge.

**Comment by dancres** [comment]
I had seen it, I appreciate the assist.

Will get to it, promise but likely it'll be the weekend (my day job is head of engineering for a large retailer so there's a *lot* to do at this time of year).

**Review by dancres — APPROVED** [review]
CIDR link doesn'r require archive, they've moved from www.cidr to cidr...

I'll merge this and fix retrospectively

**Pull request merged**
